---
title: "R Notebook"
output: html_notebook
---

The purpose of this notebook is to work through the contents of Task 5 from R - Basics. Code in this notebook has been added from the Task 5 of the R - Basics unit.

```{r}
library()
# Shows a list of R packages which are available.
```

```{r}
search()
# Executing this command currently shows 10
# R packages
```

```{r}
# The Packages tab does not contain seqinr.
?vignette
# A vignette is a useful resource for
# understanding how to write R code.
```

```{r}
?install.packages
# install.packages can install a package from  
# CRAN (the Comprehensive R Archive Network).
install.packages("seqinr",repos="https://cran.rstudio.com/") 
```

```{r}
# seqinr is now installed.
library(help="seqinr") 
library(seqinr)
```
```{r}
ls("package:seqinr")
```
```{r}
?seqinr::a
seqinr::a("Tyr")
# The output is "Y", the one letter code of 
# tyrosine.
```
```{r}
?seqinr::words
seqinr::words(3, c("A", "G", "C", "U"))
# Gives all words using the given letters.
# In this case, it gives all possible codons using
# the four bases.
```

```{r}
?data
# The function data shows data sets.
data(package="seqinr")
# For example, seqinr has the data set pK which 
# contains the pK values for charged amino acids.
```
```{r}
data(aaindex, package="seqinr") 
?aaindex
# Shows properties of the amino acids.
```

Citation:
Steipe, B. & Isserlin, R. (2020). Chapter 2 Installing R and RStudio. R - Basics. https://bcb420-2022.github.io/R_basics/r-install.html